onlyBuiltDependencies:
  - esbuild
  - prisma
  - '@prisma/client'
  - '@prisma/engines'
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
